DESIGN_NAME: bcd_converter
VERILOG_FILES:
- src/bcd_converter.sv

USE_SLANG: true

CLOCK_PERIOD: 10
CLOCK_PORT: clk

# 30% because the design is too small.
FP_CORE_UTIL: 30

FP_ASPECT_RATIO: 1.0
PL_TARGET_DENSITY: 0.55